
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int MOD = 16;
  public static final int AND = 8;
  public static final int ELSE = 12;
  public static final int PLUS = 3;
  public static final int OR = 19;
  public static final int RPAREN = 7;
  public static final int INT = 15;
  public static final int THEN = 22;
  public static final int WHILE = 24;
  public static final int CHAR = 9;
  public static final int SEMI = 2;
  public static final int NOT = 17;
  public static final int RETURN = 21;
  public static final int REF = 20;
  public static final int IF = 14;
  public static final int LPAREN = 6;
  public static final int ID = 25;
  public static final int INT_LITERAL = 27;
  public static final int STRING_LITERAL = 26;
  public static final int DO = 11;
  public static final int NOTHING = 18;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int VAR = 23;
  public static final int FUN = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "AND",
  "CHAR",
  "DIV",
  "DO",
  "ELSE",
  "FUN",
  "IF",
  "INT",
  "MOD",
  "NOT",
  "NOTHING",
  "OR",
  "REF",
  "RETURN",
  "THEN",
  "VAR",
  "WHILE",
  "ID",
  "STRING_LITERAL",
  "INT_LITERAL"
  };
}

